name: PAC & Github actions CD demo
run-name: ${{ github.actor }} is running cd workflow 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    defaults:
      run:
        working-directory: .\Solutions
    runs-on: windows-latest
    steps:
    - name: pull code
      uses: actions/checkout@v3
    - name: setup nodejs
      uses: actions/setup-node@v3
      with:
        node-version: '18.7.x'
    - name: npm install
      run: |
        echo $pwd
        node -v
        npm ci
        npm run build --if-present
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: dotnet build
      run: dotnet build
    - name: check path before publish
      run: tree /F
    - name: Import solution
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{ secrets.URL }}
        user-name:  ${{ secrets.USERNAME }}
        password-secret: ${{ secrets.PASSWORD }}
        solution-file: 'Solutions\bin\Debug\Solutions.zip'
    - name: Publish Solution
      uses: microsoft/powerplatform-actions/publish-solution@v0
      with:
        environment-url: ${{ secrets.URL }}
        user-name: ${{ secrets.USERNAME }}
        password-secret: ${{ secrets.PASSWORD }}
